### PR TITLE
apply the fix suggested by https://github.com/ocaml/ocaml-lsp/issues/…

### PR DESCRIPTION
**Pull request by mro**
…1069#issuecomment-1684916146

### CODE REVIEW

**Comment by rgrinberg** [comment]
Sorry for the obvious question, but did you test that this is enough to make it work on freebsd? Or does it just compile?

**Comment by mro** [comment]
Hi @rgrinberg,
after having said being clueless what to do and you asking for a pull request, I made exactly that. What were your expectations?

**Comment by mro** [comment]
```
$ uname -aKU
FreeBSD mx250.local 14.1-RELEASE-p5 FreeBSD 14.1-RELEASE-p5 GENERIC amd64 1401000 1401000
$ opam --version
2.1.6
$ echo $SHELL
/usr/local/bin/fish
$ git clone git@github.com:rgrinberg/lev.git ; cd lev

$ opam switch create 5.1.0
$ eval (opam env --switch=5.1.0)
$ opam install . --deps-only --with-test --with-doc --yes
$ dune build
File "lev-fiber/test/dune", line 14, characters 2-19:
14 |   ppx_expect.common
       ^^^^^^^^^^^^^^^^^
Error: Library "ppx_expect.common" not found.
-> required by library "lev_fiber_tests" in _build/default/lev-fiber/test
-> required by
   _build/default/lev-fiber/test/.lev_fiber_tests.objs/native/lev_fiber_tests__Basic.cmx
-> required by _build/default/lev-fiber/test/lev_fiber_tests.a
-> required by alias lev-fiber/test/all
-> required by alias default
...
$ opam install ppx_expect
[NOTE] Package ppx_expect is already installed (current version is v0.17.0).

$ opam switch create 4.13.1-lev 4.13.1
$ eval (opam env --switch=4.14.1-lev)
$ opam install . --deps-only --with-test --with-doc --yes
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) → ocaml-base-compiler = 4.13.1 → ocaml = 4.13.1
    - lev-fiber → ocaml >= 4.14.0
    You can temporarily relax the switch invariant with `--update-invariant'

No solution found, exiting

$ opam switch create 4.14.1-lev 4.14.1
$ opam install . --deps-only --with-test --with-doc --yes
$ dune build
/usr/local/bin/ld: warning: lev_fiber_util__Bip_buffer.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_csexp.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
lev/vendor/ev.c:514: warning: "EV_USE_INOTIFY" redefined
lev/vendor/ev.c:162: note: this is the location of the previous definition
lev/vendor/ev.c:515: warning: "EV_USE_KQUEUE" redefined
lev/vendor/ev.c:144: note: this is the location of the previous definition
lev/vendor/ev.c:2152:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern'
/usr/local/bin/ld: warning: lev.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_tests_signals.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_csexp_tests__Lev_fiber_csexp_rpc_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_tests_unix.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_tests__Basic.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_util_tests__Bip_buffer_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
$ dune runtest
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```

**Comment by rgrinberg** [comment]
Could you try again please? I fixed the ppx_expect issue

**Comment by mro** [comment]
```
$ nice opam switch create 5.1.0
…
$ nice opam switch create 5.1.0
…
$ opam install . --deps-only --with-test --with-doc --yes
…
$ dune build
File "lev/src/dune", line 16, characters 8-10:
16 |  (names ev))
             ^^
lev/vendor/ev.c:514:11: fatal error: sys/statfs.h: No such file or directory
compilation terminated.
File "_none_", line 1:                           
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                           
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                           
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                           
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
/usr/local/bin/ld: warning: lev_fiber_util__Bip_buffer.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_csexp.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
File "_none_", line 1:                           
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                          
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                          
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                          
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                          
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                          
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                          
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                          
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
/usr/local/bin/ld: warning: lev_tests_signals.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_tests_unix.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_tests__Basic.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_util_tests__Bip_buffer_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_csexp_tests__Lev_fiber_csexp_rpc_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```

**Comment by mro** [comment]
```
# click sync at github fork again
$ git pull
$ git log -3 --oneline
f6876a7 (HEAD -> master, origin/master, origin/HEAD) Merge branch 'rgrinberg:master' into master
fdc6225 chore: add missing unix deps (#100)
f8dfebe Merge branch 'rgrinberg:master' into master
$ opam switch 5.1.0 ; eval (opam env) 
$ dune clean
$ dune build
/usr/local/bin/ld: warning: lev_fiber_util__Bip_buffer.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_csexp.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
lev/vendor/ev.c:514: warning: "EV_USE_INOTIFY" redefined
lev/vendor/ev.c:162: note: this is the location of the previous definition
lev/vendor/ev.c:515: warning: "EV_USE_KQUEUE" redefined
lev/vendor/ev.c:144: note: this is the location of the previous definition
lev/vendor/ev.c:2152:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern'
/usr/local/bin/ld: warning: lev.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
File "_none_", line 1:                 
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:                
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
/usr/local/bin/ld: warning: lev_tests_signals.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_tests_unix.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_csexp_tests__Lev_fiber_csexp_rpc_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_tests__Basic.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_fiber_util_tests__Bip_buffer_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: lev_tests.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker

$ dune test
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/local/bin/ld: warning: amd64.o: missing .note.GNU-stack section implies executable stack
/usr/local/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```

**Comment by rgrinberg** [comment]
Thanks!

**Comment by mro** [comment]
Hi @rgrinberg,
just wanted to 

```
$ opam switch
#  switch  compiler                    description
   4.12.1  ocaml-base-compiler.4.12.1  4.12.1
→  4.14.2  ocaml-base-compiler.4.14.2  4.14.2
   5.2.1   ocaml-base-compiler.5.2.1   5.2.1
$ opam install ocaml-lsp-server
...
[ERROR] The compilation of ocaml-lsp-server.1.20.1-4.14 failed at "dune build -p ocaml-lsp-server -j 3 @install".

#=== ERROR while compiling ocaml-lsp-server.1.20.1-4.14 =======================#
# context     2.1.6 | freebsd/x86_64 | ocaml-base-compiler.4.14.2 | https://opam.ocaml.org#92bf71cef0f7dba40647ad4c55d91e8125280ed8
# path        /usr/home/mro/.opam/4.14.2/.opam-switch/build/ocaml-lsp-server.1.20.1-4.14
# command     /usr/home/mro/.opam/4.14.2/bin/dune build -p ocaml-lsp-server -j 3 @install
# exit-code   1
# env-file    /usr/home/mro/.opam/log/ocaml-lsp-server-77618-8c29ca.env
# output-file /usr/home/mro/.opam/log/ocaml-lsp-server-77618-8c29ca.out
### output ###
# File "ocaml-lsp-server/dune", line 43, characters 21-23:
# 43 |     (names lev_stubs ev)))))
#                           ^^
# (cd _build/default/ocaml-lsp-server/vendor/lev && /usr/local/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -fdiagnostics-color=always -g -I /usr/home/mro/.opam/4.14.2/lib/ocaml -o ev.o -c ev.c)
# submodules/lev/lev/vendor/ev.c:510:11: fatal error: sys/statfs.h: No such file or directory
# compilation terminated.
```

What should I do do benefit from the lsp server?

**Pull request merged**
